Fix issue #27
torrent-proxy/web-app pull request #28
Opened 2020-10-29 17:12 UTC by apoluektova

2020-10-30 09:20 UTC, kicumkicum commented
Я неправильно выразился, когда объяснял. Я имел ввиду, что заголовок должен быть информационным, а в описании написать fixes, для линковки. Вот тут можно почитать https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

2020-10-30 09:21 UTC, kicumkicum commented
@apoluektova Устанавливай меня ревьюром, так я буду дополнительно получать уведомление на почту о созданном ПРе.

2020-10-30 09:59 UTC, kicumkicum requested changes
Запустил проек - оч круто. Если бы я был настоящим заказчиком, то офигел бы. Только обсудили, а на следующий день уже что-то можно посмотреть. Здорово!

Все очень классно для первого приближения. Структура App, структура Header просто огонь. Потом они немного изменятся, потому что появятся страницы и появится больше представления. Но на текущий момент лучше быть просто не может. Отличная работа 💪🏽

2020-10-30 09:59 UTC, kicumkicum commented on package.json
> +    "eslint.ts": "eslint --config .eslintrc-ts.yml --ext .tsx src/",
давай  переименуем скрипты `eslint*` в `lint`. Потому что задача - линтинг. А еслинт как особенность реализации.

2020-10-30 09:59 UTC, kicumkicum commented on package.json
> +    "react-router-dom": "5.2.0",
Эта зависимость нам пока не нужна

2020-10-30 09:59 UTC, kicumkicum commented on package.json
> +    "history": "4.9.0",
и эта

2020-10-30 09:59 UTC, kicumkicum commented on package.json
> +    "axios": "0.19.2",
и эта

2020-10-30 09:59 UTC, kicumkicum commented on package.json
> +    "reselect": "4.0.0"
Давай пока оставим `react, react-dom`. Без всего остального сейчас можем жить. Доставим их когда потребуются. А то может мы вообще решим какой-нибудь mobx использовать)))

2020-10-30 09:59 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +export default App;
Тут и в остальных местах не хватает пустой строки в конце файла. По идее едиторконфиг должен был решать эту проблему. Посмотри, есть ли там соответствующая настройка

2020-10-30 09:59 UTC, kicumkicum commented on src/components/color-theme/color-theme.component.tsx
> +    <React.Fragment>
Ты специально тут используешь фрагмент?

2020-10-30 09:59 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +import * as React from "react";
если в конфиге ТСа сделать `allowSyntheticDefaultImport: true`, то можно писать `import React from "react"`

2020-10-30 09:59 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +import DownloadButton from "../download-button/download-button.component";
Создай ишью на добавление правила в еслинт для сортировки зависимостей в abc-сортировке. Сделаем его позже, чтобы не блокировать этот ПР

2020-10-30 09:59 UTC, kicumkicum commented on src/components/search-results/search-results.component.tsx
> +      <table className="search-results__table table">
Расскажешь потом, как ты придумываешь имена для css-классов? А то для меня это одна из самых больших загадок мира)

2020-11-01 12:38 UTC, kicumkicum commented on src/components/color-theme/color-theme.component.tsx
> +    <React.Fragment>
done

2020-11-01 12:47 UTC, kicumkicum commented on package.json
> +    "eslint.ts": "eslint --config .eslintrc-ts.yml --ext .tsx src/",
done

2020-11-01 12:47 UTC, kicumkicum commented on package.json
> +    "react-router-dom": "5.2.0",
done

2020-11-01 12:47 UTC, kicumkicum commented on package.json
> +    "history": "4.9.0",
done

2020-11-01 12:47 UTC, kicumkicum commented on package.json
> +    "axios": "0.19.2",
done

2020-11-01 12:48 UTC, kicumkicum commented on package.json
> +    "reselect": "4.0.0"
done

2020-11-01 12:49 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +import DownloadButton from "../download-button/download-button.component";
done #29

2020-11-01 12:50 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +import * as React from "react";
Давай уберем все эти звездочки из импортов, раз конфиг поменяли

2020-11-01 12:51 UTC, kicumkicum commented on src/components/app/app.component.tsx
> +export default App;
Ты удалила строчку из едиторконфига и все заработало? Как будто бы та строчка как раз и должна была решать эту проблему, не?

2020-11-01 13:44 UTC, apoluektova commented on src/components/app/app.component.tsx
> +export default App;
Почему-то эта строчка там была дважды, теперь файлы сохраняются как надо.

2020-11-01 13:49 UTC, apoluektova commented on src/components/app/app.component.tsx
> +import * as React from "react";
done

2020-11-01 15:15 UTC, kicumkicum approved these changes

2020-11-01 15:16 UTC, merged